import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#121412",
        "surface-dim": "#121412",
        "surface-bright": "#383a38",
        "surface-container-lowest": "#0d0f0d",
        "surface-container-low": "#1a1c1a",
        "surface-container": "#1e201e",
        "surface-container-high": "#292a29",
        "surface-container-highest": "#333533",
        "on-surface": "#e3e3e0",
        "on-surface-variant": "#c1c8c2",
        "inverse-surface": "#e3e3e0",
        "inverse-on-surface": "#2f312f",
        outline: "#8b928d",
        "outline-variant": "#414844",
        "surface-tint": "#aacfb9",
        primary: "#aacfb9",
        "on-primary": "#153627",
        "primary-container": "#8baf9a",
        "on-primary-container": "#214332",
        "inverse-primary": "#446553",
        secondary: "#c6c6cb",
        "on-secondary": "#2f3035",
        "secondary-container": "#4a4b50",
        "on-secondary-container": "#bbbbc1",
        tertiary: "#f0b9b9",
        "on-tertiary": "#4a2627",
        "tertiary-container": "#ce9a9a",
        "on-tertiary-container": "#573233",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#121412",
        "on-background": "#e3e3e0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "240px",
        "sidebar-collapsed": "64px",
        gutter: "24px",
        "container-padding": "32px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
      },
      fontFamily: {
        sans: ["Geist", "Inter", "system-ui", "sans-serif"],
        display: ["Geist", "Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Geist", "Inter", "sans-serif"],
        "body-md": ["Geist", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "mono-data": ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
export default config;

