import {
  Profile,
  Topic,
  TopicPrerequisite,
  Question,
  UserTopicMastery,
  Goal,
  Attempt,
  DailyActivity,
  Streak,
  XPTransaction,
  DSAExperience,
} from '@/lib/types';

export const INITIAL_TOPICS: Topic[] = [
  { id: 'arrays', name: 'Arrays', description: 'Contiguous memory blocks, indexing, and array manipulations', created_at: new Date().toISOString() },
  { id: 'hashing', name: 'Hashing', description: 'Hash maps and hash sets for O(1) lookups', created_at: new Date().toISOString() },
  { id: 'two_pointers', name: 'Two Pointers', description: 'Using two indices to iterate through a sorted array or linear structure', created_at: new Date().toISOString() },
  { id: 'sliding_window', name: 'Sliding Window', description: 'Dynamic window bounds over arrays/strings', created_at: new Date().toISOString() },
  { id: 'prefix_sum', name: 'Prefix Sum', description: 'Precomputing cumulative sums for dynamic subarray queries', created_at: new Date().toISOString() },
  { id: 'binary_search', name: 'Binary Search', description: 'Logarithmic search space reduction', created_at: new Date().toISOString() },
  { id: 'linked_lists', name: 'Linked Lists', description: 'Node based linear data structures and pointer shifts', created_at: new Date().toISOString() },
  { id: 'stack', name: 'Stack', description: 'LIFO operations for parenthesis matching and monotonic stacks', created_at: new Date().toISOString() },
  { id: 'queue', name: 'Queue', description: 'FIFO queues and double ended queue manipulations', created_at: new Date().toISOString() },
  { id: 'recursion', name: 'Recursion', description: 'Base cases and recursive tree branching', created_at: new Date().toISOString() },
  { id: 'backtracking', name: 'Backtracking', description: 'State space tree search with pruning', created_at: new Date().toISOString() },
  { id: 'trees', name: 'Trees', description: 'Binary tree traversals, node properties, and recursion', created_at: new Date().toISOString() },
  { id: 'bst', name: 'BST', description: 'Binary Search Tree properties, search, and insertion', created_at: new Date().toISOString() },
  { id: 'graphs', name: 'Graphs', description: 'Vertices and edges representation (Adjacency list/matrix)', created_at: new Date().toISOString() },
  { id: 'bfs', name: 'BFS', description: 'Breadth-First Search level order traversal and shortest paths', created_at: new Date().toISOString() },
  { id: 'dfs', name: 'DFS', description: 'Depth-First Search path exploration and connected components', created_at: new Date().toISOString() },
  { id: 'heap', name: 'Heap / Priority Queue', description: 'Min-heap and max-heap operations for k-way selection', created_at: new Date().toISOString() },
  { id: 'greedy', name: 'Greedy', description: 'Locally optimal choice heuristics for global optimization', created_at: new Date().toISOString() },
  { id: 'dp', name: 'Dynamic Programming', description: 'Memoization, tabulation, and optimal substructure', created_at: new Date().toISOString() },
];

export const INITIAL_PREREQUISITES: TopicPrerequisite[] = [
  { topic_id: 'hashing', prerequisite_id: 'arrays' },
  { topic_id: 'two_pointers', prerequisite_id: 'hashing' },
  { topic_id: 'sliding_window', prerequisite_id: 'two_pointers' },
  { topic_id: 'backtracking', prerequisite_id: 'recursion' },
  { topic_id: 'bst', prerequisite_id: 'trees' },
  { topic_id: 'bfs', prerequisite_id: 'graphs' },
  { topic_id: 'dfs', prerequisite_id: 'graphs' },
];

export const INITIAL_QUESTIONS: Question[] = [
  // Arrays & Hashing
  {
    id: 'q_two_sum',
    title: 'Two Sum',
    slug: 'two-sum',
    leetcode_url: 'https://leetcode.com/problems/two-sum/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'hashing',
    secondary_topics: ['arrays'],
    pattern: 'Hash Map Lookup',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_contains_duplicate',
    title: 'Contains Duplicate',
    slug: 'contains-duplicate',
    leetcode_url: 'https://leetcode.com/problems/contains-duplicate/',
    difficulty: 'EASY',
    estimated_time: 10,
    primary_topic_id: 'arrays',
    secondary_topics: ['hashing'],
    pattern: 'Hash Set Frequency',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_valid_anagram',
    title: 'Valid Anagram',
    slug: 'valid-anagram',
    leetcode_url: 'https://leetcode.com/problems/valid-anagram/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'hashing',
    secondary_topics: ['arrays'],
    pattern: 'Frequency Counter',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_group_anagrams',
    title: 'Group Anagrams',
    slug: 'group-anagrams',
    leetcode_url: 'https://leetcode.com/problems/group-anagrams/',
    difficulty: 'MEDIUM',
    estimated_time: 25,
    primary_topic_id: 'hashing',
    secondary_topics: ['arrays'],
    pattern: 'Categorization Key Hash',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_top_k_frequent',
    title: 'Top K Frequent Elements',
    slug: 'top-k-frequent-elements',
    leetcode_url: 'https://leetcode.com/problems/top-k-frequent-elements/',
    difficulty: 'MEDIUM',
    estimated_time: 25,
    primary_topic_id: 'hashing',
    secondary_topics: ['heap'],
    pattern: 'Bucket Sort / Priority Queue',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Two Pointers & Sliding Window
  {
    id: 'q_valid_palindrome',
    title: 'Valid Palindrome',
    slug: 'valid-palindrome',
    leetcode_url: 'https://leetcode.com/problems/valid-palindrome/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'two_pointers',
    secondary_topics: ['arrays'],
    pattern: 'Two Pointers Inward',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_3sum',
    title: '3Sum',
    slug: '3sum',
    leetcode_url: 'https://leetcode.com/problems/3sum/',
    difficulty: 'MEDIUM',
    estimated_time: 30,
    primary_topic_id: 'two_pointers',
    secondary_topics: ['arrays'],
    pattern: 'Sorted Array Two Pointers',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_container_water',
    title: 'Container With Most Water',
    slug: 'container-with-most-water',
    leetcode_url: 'https://leetcode.com/problems/container-with-most-water/',
    difficulty: 'MEDIUM',
    estimated_time: 25,
    primary_topic_id: 'two_pointers',
    secondary_topics: ['arrays'],
    pattern: 'Greedy Two Pointers Inward',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_best_time_stock',
    title: 'Best Time to Buy and Sell Stock',
    slug: 'best-time-to-buy-and-sell-stock',
    leetcode_url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'sliding_window',
    secondary_topics: ['arrays'],
    pattern: 'Sliding Window Max Profit',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_longest_substring_no_repeat',
    title: 'Longest Substring Without Repeating Characters',
    slug: 'longest-substring-without-repeating-characters',
    leetcode_url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    difficulty: 'MEDIUM',
    estimated_time: 25,
    primary_topic_id: 'sliding_window',
    secondary_topics: ['hashing'],
    pattern: 'Dynamic Window Hash Set',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Binary Search
  {
    id: 'q_binary_search',
    title: 'Binary Search',
    slug: 'binary-search',
    leetcode_url: 'https://leetcode.com/problems/binary-search/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'binary_search',
    secondary_topics: ['arrays'],
    pattern: 'Classic Binary Search',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_search_2d_matrix',
    title: 'Search a 2D Matrix',
    slug: 'search-a-2d-matrix',
    leetcode_url: 'https://leetcode.com/problems/search-a-2d-matrix/',
    difficulty: 'MEDIUM',
    estimated_time: 20,
    primary_topic_id: 'binary_search',
    secondary_topics: ['arrays'],
    pattern: '2D Array Flat Binary Search',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_koko_bananas',
    title: 'Koko Eating Bananas',
    slug: 'koko-eating-bananas',
    leetcode_url: 'https://leetcode.com/problems/koko-eating-bananas/',
    difficulty: 'MEDIUM',
    estimated_time: 30,
    primary_topic_id: 'binary_search',
    secondary_topics: ['greedy'],
    pattern: 'Binary Search on Answer Space',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Linked Lists / Stack
  {
    id: 'q_reverse_linked_list',
    title: 'Reverse Linked List',
    slug: 'reverse-linked-list',
    leetcode_url: 'https://leetcode.com/problems/reverse-linked-list/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'linked_lists',
    secondary_topics: [],
    pattern: 'Iterative Pointer Mutation',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_valid_parentheses',
    title: 'Valid Parentheses',
    slug: 'valid-parentheses',
    leetcode_url: 'https://leetcode.com/problems/valid-parentheses/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'stack',
    secondary_topics: ['hashing'],
    pattern: 'Bracket Stack Matching',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Trees / BST
  {
    id: 'q_invert_binary_tree',
    title: 'Invert Binary Tree',
    slug: 'invert-binary-tree',
    leetcode_url: 'https://leetcode.com/problems/invert-binary-tree/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'trees',
    secondary_topics: ['dfs'],
    pattern: 'Recursive Postorder Traversal',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_validate_bst',
    title: 'Validate Binary Search Tree',
    slug: 'validate-binary-search-tree',
    leetcode_url: 'https://leetcode.com/problems/validate-binary-search-tree/',
    difficulty: 'MEDIUM',
    estimated_time: 25,
    primary_topic_id: 'bst',
    secondary_topics: ['trees', 'dfs'],
    pattern: 'Inorder Bounds Check',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Graphs / DFS / BFS
  {
    id: 'q_number_of_islands',
    title: 'Number of Islands',
    slug: 'number-of-islands',
    leetcode_url: 'https://leetcode.com/problems/number-of-islands/',
    difficulty: 'MEDIUM',
    estimated_time: 25,
    primary_topic_id: 'dfs',
    secondary_topics: ['graphs', 'bfs'],
    pattern: 'Grid Connected Components',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Dynamic Programming
  {
    id: 'q_climbing_stairs',
    title: 'Climbing Stairs',
    slug: 'climbing-stairs',
    leetcode_url: 'https://leetcode.com/problems/climbing-stairs/',
    difficulty: 'EASY',
    estimated_time: 15,
    primary_topic_id: 'dp',
    secondary_topics: ['recursion'],
    pattern: 'Fibonacci DP Tabulation',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_house_robber',
    title: 'House Robber',
    slug: 'house-robber',
    leetcode_url: 'https://leetcode.com/problems/house-robber/',
    difficulty: 'MEDIUM',
    estimated_time: 25,
    primary_topic_id: 'dp',
    secondary_topics: ['arrays'],
    pattern: 'State Machine Choice DP',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_coin_change',
    title: 'Coin Change',
    slug: 'coin-change',
    leetcode_url: 'https://leetcode.com/problems/coin-change/',
    difficulty: 'MEDIUM',
    estimated_time: 30,
    primary_topic_id: 'dp',
    secondary_topics: ['bfs'],
    pattern: 'Unbounded Knapsack Tabulation',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q_long_increasing_subsequence',
    title: 'Longest Increasing Subsequence',
    slug: 'longest-increasing-subsequence',
    leetcode_url: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    difficulty: 'HARD',
    estimated_time: 35,
    primary_topic_id: 'dp',
    secondary_topics: ['binary_search'],
    pattern: 'DP / Binary Search Optimization',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
